type: object
properties:
  id:
    type: string
    format: int64
    description: Unique identifier for the product.
    readOnly: true
    example: 123456789
  name:
    type: string
    description: Name of the product.
    minLength: 2
    maxLength: 100
    example: Product Name
  description:
    type: string
    description: Description of the product.
    maxLength: 500
    example: Product Description
  dimensions:
    $ref: 'dimensions.yaml'
  categories:
    type: array
    items:
      $ref: 'category.yaml'
    minItems: 1
    example:
      - id: 1
        name: Category Name
  images:
    type: array
    items:
      $ref: 'image.yaml'
    minItems: 1
    example:
      - url: http://example.com/image.jpg
        altText: Image description
  price:
    type: string
    pattern: ^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$
    example: 19.99
  cost:
    type: string
    pattern: ^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}$
    example: 9.99
  dateCreated:
    $ref: '../common/iso_timestamp.yaml'
  dateUpdated:
    $ref: '../common/iso_timestamp.yaml'
required:
  - name
  - description
  - dimensions
  - categories
  - images
  - price
  - cost